### ISSUE TITLE
server crashes when uploading scripts per command line

### ISSUE THREAD

**Issue by wehrstedt** [otris/node-documents-scripting#6]
As discussed (with @bkircher):

Sometimes the server crashes when I upload a script per command line. It only happens when I upload the script per command line. If I upload the same script per vs code extension, everything works fine. Also it only happens with some scripts. If I remove some source code of the script which causes the crash, it works, but there is no pattern recognizable.

First, I thought its because of different versions of the node-sds module. The node-documents-scripting module requires version 1.0.0, the vs code extension version 1.1.0. An update can't resolve the problem.

Steps to reproduce:
1. Checkout the node-documents-scripting module
2. Download scripts from my public folder: wehrstedt\\github-issue\\ (I don't want to publish the scripts here because everyone can see it)
3. Run the following commands:
    node out/src/cmd.js upload .vscode/launch.json "crash-script.js"
    node out/src/cmd.js upload .vscode/launch.json "working-script.js"

Im using documents 5.0b#2034

**Comment by wehrstedt** [comment]
This is an example output when the server crashes:
![crashing](https://user-images.githubusercontent.com/27811714/29172331-f28c0dfa-7ddf-11e7-805b-404842fcc92e.png)

**Comment by wehrstedt** [comment]
This is an example output if it works:
![working](https://user-images.githubusercontent.com/27811714/29172423-36844da6-7de0-11e7-88be-590ecf2f5088.png)

**Comment by wehrstedt** [comment]
Hmm..tested the "workingScript" again, now even this script won't upload...

**Comment by tineheller** [comment]
This is an utf8 problem, it will be fixed in [node-sds](https://github.com/otris/node-sds).
